version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: passgo
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/pg-init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "user", "-d", "passgo" ]
      interval: 5s
      retries: 5
      timeout: 3s
    networks:
      - passgo-network

  app:
    build: .
    container_name: passgo_app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "9090:8080"
    env_file:
      - .env
    restart: unless-stopped
    entrypoint: ["/bin/sh", "-c", "echo 'Waiting for DB...'; sleep 2; java -Dspring.profiles.active=dev -jar app.jar"]
    networks:
      - passgo-network

volumes:
  pgdata:

networks:
  passgo-network:
    driver: bridge