spring:
  config:
    import: optional:file:.env[.properties]
  profiles:
    default: local
  application:
    name: ${PROJECT_NAME}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  flyway:
    enabled: false
  lifecycle:                                # NEW: Adds a timeout for graceful shutdown
    timeout-per-shutdown-phase: 10s         # NEW
  devtools:
    livereload:
      enabled: false

server:
  port: 8080
  shutdown: graceful                        # NEW: Tells Tomcat to shut down gracefully
  servlet:
    context-path: /rest-api

springdoc:
  swagger-ui:
    enabled: false

app:
  configuration:
    security:
      enabled: true
  upload-dir: uploads