spring:
  application:
    name: ${APP_NAME:prod_profile}
  config:
    import: optional:file:env/.env.prod[.properties]
  jpa:
    hibernate:
      ddl-auto: validate

app:
  configuration:
    security:
      enabled: false
