spring:
  application:
    name: ${APP_NAME:local}
  config:
    import: optional:file:env/.env.local[.properties]
  jpa:
    hibernate:
      ddl-auto: validate

logging:
  level:
    org.springframework: INFO