spring:
  datasource:
    url: jdbc:h2:mem:${H2_DB:testdb}
    driver-class-name: org.h2.Driver
    username: ${H2_USER:sa}
    password: ${H2_PASSWORD:}
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
  h2:
    console:
      enabled: true
      path: /h2-console
  security:
    user:
      name: ${BASE_AUTH_LOGIN:admin}
      password: ${BASE_AUTH_PASSWORD:admin}

logging:
  level:
    org.springframework.security: TRACE

app:
  configuration:
    security:
      enabled: false
