ALTER TABLE building
    ADD COLUMN approved BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE event
    ADD COLUMN approved BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE sector
    ADD COLUMN standing_area NOT NULL;