-- migration fix
ALTER TABLE seat
    ADD COLUMN seat_number BIGINT NOT NULL;

CREATE TABLE ticket_sale
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seller_id       BIGINT REFERENCES client(id) ON DELETE CASCADE NOT NULL,
    buyer_id        BIGINT REFERENCES client(id) ON DELETE CASCADE,
    ticket_id       BIGINT REFERENCES ticket(id) ON DELETE CASCADE NOT NULL,
    price           NUMERIC(38, 2) NOT NULL,
    status          VARCHAR(50) NOT NULL
);

ALTER TABLE ticket
    ADD COLUMN status VARCHAR(50) NOT NULL DEFAULT 'AVAILABLE';

