name: Passgo-verify-deploy

on:
  push:
    branches: ["workflow-dev"]

jobs:
  build:
    name: Maven verify and upload
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project files
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Setup maven
        run: chmod u+x ./mvnw

      - name: Build with Maven
        run: ./mvnw --batch-mode --update-snapshots verify

      - name: Create and copy artifact directory
        run: mkdir staging && cp target/passgo-*.jar staging

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: passgo-artifact
          path: staging